### ISSUE TITLE
Unable to add indicator when the series is added dynamically

### ISSUE THREAD

**Issue by arnabk** [blacklabel/indicators#16]
Please refer to this JSFiddle http://jsfiddle.net/arnabk/74dzr6gz/3/

**Comment by pawelfus** [comment]
Please refer to this docs: https://github.com/blacklabel/indicators 

> id:	id of series

And: 

> type: type of indicator (one of: 'sma', 'ema', 'atr', 'rsi')


Working demo: http://jsfiddle.net/74dzr6gz/4/

**Comment by arnabk** [comment]
Please check this example. Open console to see the error message.
http://jsfiddle.net/arnabk/74dzr6gz/7/
![image](https://cloud.githubusercontent.com/assets/446864/6550894/2d390ff2-c5f5-11e4-89f8-6ec7be2498b5.png)

**Comment by pawelfus** [comment]
That part looks like a bug. Reopening

**Comment by pawelfus** [comment]
If you are in hurry, you can edit  `#982` line:

    if(exportingFlag && chart.series[0]) {
    ...
    }

I think that should be enough, I will check `exportingFlag` - if this is even required still.
