### ISSUE TITLE
Indicators update axes unnecessary

### ISSUE THREAD

**Issue by pawelfus** [blacklabel/indicators#18]
Compare examples:

- http://jsfiddle.net/2ajhyhm4/ (w/ indicators)
- http://jsfiddle.net/2ajhyhm4/1/ (w/o indicators)

Indicators shouldn't update axes when it's not necessary. Performance and logic issue. 

**Internal note:** <br> It may be necessary to create logic when chart contains more than default one yAxis. Consider example when two y-axes are set (`height: "65%"` + `height: "35%"`) and we need to add new yAxis for an indicator. Right now all axes will get **the same height**, calculated in `var newHeight = chart.updateHeightAxes(diff, add);` method. 

It may be good idea to check if options are set in `userOptions` or calculated by Highcharts source.

**Comment by sebastianbochan** [comment]
**Internal note: **
Consider top / height parameters per extra axis (RSI / ATR etc)
