### ISSUE TITLE
dataGrouping - forced param issue

### ISSUE THREAD

**Issue by sebastianbochan** [blacklabel/indicators#23]
1) Run example http://jsfiddle.net/RE7sS/163/
2) Set range as screenshot 1
3) Move range to right, slowly (screenshot 2) 
4) SMA is incorrect printed, when you scroll. Line stays at the same position (after 14 points) despite fact that you have more than 14 points at the beginning.

![zrzut ekranu 2015-04-09 o 14 40 11](https://cloud.githubusercontent.com/assets/2115686/7066795/597602d4-dec6-11e4-81c1-3c947b6d09af.png)

![zrzut ekranu 2015-04-09 o 14 38 40](https://cloud.githubusercontent.com/assets/2115686/7066775/2b32e9a0-dec6-11e4-9664-bd08b048d0d6.png)

**Comment by pawelfus** [comment]
In short: SMA is missing points at the beginning, where grouping is used (indicators grouping).

**Comment by pawelfus** [comment]
Note: Broken since Highstock v1.3.6.
