### ISSUE TITLE
What's the licence

### ISSUE THREAD

**Issue by meh-uk** [blacklabel/indicators#36]
Hey

I see this is licenced under creative commons, however which creative commons licence is it licenced with?

**Comment by pawelfus** [comment]
[Here](https://github.com/blacklabel/indicators/blob/master/license.txt) you can find license.

**Comment by meh-uk** [comment]
Right, but which creative commons licence is that? CC BY? CC BY-SA? And which version? 4.0?

**Comment by pawelfus** [comment]
Ah, sorry.
It's CC BY-SA 4.0.

**Comment by meh-uk** [comment]
Thanks :). I've created a pull request (#37) to add this to the licence file itself.
