### ISSUE TITLE
Indicator with specific axis miscalculates extremes

### ISSUE THREAD

**Issue by pawelfus** [blacklabel/indicators#38]
Demo: http://jsfiddle.net/RE7sS/205/

RSI is clipped on top, while yAxis should rescale itself.

**Comment by PhilTheAir** [comment]
In the 72 line of the demo( http://jsfiddle.net/RE7sS/205/ ),
adv_options.series[0].type = 'candlestick';

When change the type 'candlestick' to 'line' in the code above, the two button will not work.
Maybe the potential problem is the data the indicator is utilizing has change to the data which draws the line in the chart ( yAxis for the line is only a one dimension array), not the data drawing the candlestick ( whose yAxis array's elements have 4 values). Any idea how to handle this ... ?

**Comment by PhilTheAir** [comment]
new pull request:
https://github.com/blacklabel/indicators/pull/46
