### ISSUE TITLE
Setting indicator height

### ISSUE THREAD

**Issue by priikone** [blacklabel/indicators#39]
Is there a way to specify the heigh of an idicator.  Can't find any in the API.  Is there some undocumented function I could call to achieve it?

**Comment by pawelfus** [comment]
Could explain what do you mean by height of the indicator? For example for RSI/ATR set `yAxis.height` in options.

**Comment by priikone** [comment]
Ok, seems to work but only when either RSI and ATR are present.  If both are then only the last pane respects the height.

What I was thinking is that I could have default size for indicators and the main chart area would be as large as it can be, and would get smaller or larger depending on number of indicator panes present and would scale as window size is changed but the indicators would stay the same size.

**Comment by pawelfus** [comment]
I think this is implemented by https://github.com/blacklabel/indicators#new-optionsmethods-in-chart - `alignAxes` option. Could you confirm?

**Comment by pawelfus** [comment]
Please, reopen ticket if you still have any issues with heights.
