### ISSUE TITLE
calling setVisible with legend/disabled, showInLegend/enabled breaks showing/hiding

### ISSUE THREAD

**Issue by morganfree** [blacklabel/indicators#43]
Tries to call colorizeItem() on undefined object (legend). Checking if legend is enabled in Indicator's setVisible method seems to solve this.

**Comment by pawelfus** [comment]
Closed as merged #44.

**Comment by morganfree** [comment]
The error appears again, possible after the change https://github.com/blacklabel/indicators/commit/511fe9668f57ba12c0c49a840dadb0d6c0d3e9b5#diff-63c800012b9fc58905dbfd61e40cc229L880

Demo: http://jsfiddle.net/x4p3v9wx/
Click on button - colorizeItem is called.

**Comment by pawelfus** [comment]
Fixed in version 2.1.4.
