### ISSUE TITLE
After destroying an indicator, tooltip of the connected series still has the indicator info.

### ISSUE THREAD

**Issue by KacperMadej** [blacklabel/indicators#51]
As in the title.

Demo: http://jsfiddle.net/RE7sS/395/

Steps:
1. Click the button to remove ATR
2. Hover over series to find ATR in tooltip

Workaround (by **pawelfus**) for dynamically added indicators:

```
Highcharts.charts[0].series[0].isDirtyData = true;
Highcharts.charts[0].indicators.allItems[0].destroy(false);
Highcharts.charts[0].redraw();
```
Demo: http://jsfiddle.net/nz0peu33/8/

**Comment by KacperMadej** [comment]
Fix suggestion: in [Indicator.prototype.destroy()](https://github.com/blacklabel/indicators/blob/master/js/indicators.js#L857-L858) use `tooltipkey`.

**Comment by lakshmikant4u** [comment]
@pawelfus When can we expect new release which has this fix? It would be great if we have it ASAP.

**Comment by pawelfus** [comment]
Hi @lakshmikant4u 

Thank you for the reminder. Version 2.1.5 released.

**Comment by lakshmikant4u** [comment]
Thanks @pawelfus .
