### ISSUE TITLE
indicator.destory() not working after modifying yAxis.

### ISSUE THREAD

**Issue by BDChaudhari90** [blacklabel/indicators#52]
On updating yAxis indicator.destroy() not working...

Steps to replicate issue.
1. Add an indicator which have separate yAxis. (i.e - RSI / ATR..)
2. Now update yAxis where indicator belongs. (i.e Chart.yAxis[2].update({top:'20%'});)
3. Now redraw graph so that Indicator will be displayed on updated yAxis.
     Chart.indicators.allItems[0].drawGraph();

4. Now try to destroy that Indicator using indicator.destroy() (It will not work)
    Chart.indicators.allItems[0].destroy();

Indicator will be destroyed but yAxis will be there....

**Comment by pawelfus** [comment]
Thanks for reporting this issue!

Workaround:

`Highcharts.Axis.prototype.keepProps.push('indicators');`

**Comment by BDChaudhari90** [comment]
Many thanks @pawelfus ,

Above solution worked for me.
Now I am manually setting height and top of indicator yAxis and it looks fine.
