### ISSUE TITLE
Issue while updating series from 'CandleStick' to 'Line'

### ISSUE THREAD

**Issue by BDChaudhari90** [blacklabel/indicators#54]
Hello Team,

We already raised issue to Support team and got reply with below GitHub link
https://github.com/highcharts/highcharts/issues/2322

But still We are facing issue while updating series from 'Candlestick' to 'Line' and again from 'Line' to 'Line'.

Below are the exact steps to replicate issue.
Click on JsFiddle - http://jsfiddle.net/BDChaudhari90/97651yvn/10/

1. Here the chart will be loaded with candlestick type initially.
2. Now change it to Line by clicking on "change to line" button.  (Chart will be changed to line.)
3. Now click on 'Again change to Line' button. (This is causing issue.)
4. Now again change to candlestick it will work.

If above GitHub link is the workaround for the same then how can we replace all the methods of the prototype object ?

**Comment by pawelfus** [comment]
Hi,

Wrong repo ;) It's for the Indicators plugin, the the Highcharts/Highstock core.
