### ISSUE TITLE
How to create 'super trend' study with highstock/highchart

### ISSUE THREAD

**Issue by RamDivrania** [blacklabel/indicators#64]
How to create 'super trend' study with highstock/highchart.
Please help

**Comment by sebastianbochan** [comment]
Hi @RamDivrania,
Thank you for contacting us. At this moment the indicator is not included in our package, but you can create it on your own. 

I advise you to familiar with our article about creating custom indicators here: https://www.highcharts.com/blog/products/highcharts/creating-custom-technical-indicators-financial-charts/
